---
- import_tasks: openvpn-2.4-xenial-apt-repo.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Update apt packages
  apt:
    update-cache: yes
    upgrade: 'yes'
    cache_valid_time: 14400 # Valid for 4 hours.
